#!/usr/bin/env bash
#
# Example usage:
# $ ./docs/examples/gen docs/examples/test/basic_test.exs
#   [clip]
#   Creating docs/examples/gifs/basic_test.gif...

set -Euo pipefail

exs_file=${1?pass a path to .exs as argument}
if [[ ! -f $exs_file ]]; then
  echo 'File $exs_file does not exist'
  exit
fi

dir=$(dirname "$0")
example_basename=$(basename "${exs_file}" .exs)
output="$dir/gifs/$example_basename.gif"
tmp_test="$dir/example.exs"

cp $exs_file $tmp_test
vhs "$dir/gen.tape" -o $output
rm $tmp_test
